operations:
  view:
    - type: web
      impl: index.html
actions: actions
web: web-src
hooks:
  pre-app-build: src/commerce-backend-ui-1/hooks/pre-app-build.js
  pre-app-deploy: src/commerce-backend-ui-1/hooks/pre-app-deploy.js
runtimeManifest:
  packages:
    example:
      license: Apache-2.0
      actions:
        $include: actions/example/actions.config.yaml
    commerce-backend-ui-1:
      license: Apache-2.0
      actions:
        generic:
          function: ../../build/actions/generic/index.js
          web: 'yes'
          runtime: nodejs:22
          inputs:
            LOG_LEVEL: debug
          annotations:
            require-adobe-auth: true
            final: true
