registration:
  function: ../../../../build/actions/commerce-backend-ui-1/registration/index.js
  web: 'yes'
  runtime: nodejs:22
  inputs:
    LOG_LEVEL: debug
  annotations:
    require-adobe-auth: true
    final: true
